server {
  listen 80;
  server_name _;
  root /usr/share/nginx/html;
  index index.html;

  # SPA: wszystkie nieznane ścieżki obsługuje index.html (routing po stronie klienta)
  location / {
    try_files $uri $uri/ /index.html;
  }
}
